replicaCount: 2

image:
  repository: rajuray143/demo_spring_with_argo
  tag: "5"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 9090
serviceAccount:
  create: true
  name: myapp-sa

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80